# List of questions similar to "what can you see?"
similar_questions = [
    "What do you see?",
    "Can you spot the brown box?",
    "Are you able to view the box?",
    "What's within your field of vision?",
    "Describe what's in front of you.",
    "Tell me about the objects you can see.",
    "Do you notice anything in particular?",
    "Is there anything in your line of sight?",
    "Can you describe your surroundings?",
    "What's in your visual range?",
    "Are there any items you can observe?",
    "Can you identify any objects nearby?",
    "Tell me what you're looking at.",
    "Is there anything catching your eye?",
    "Describe the things you can perceive.",
    "What's within your gaze?",
    "Share your visual impressions.",
    "Are there any items of interest?",
    "Can you make out any shapes or colors?",
    "Tell me about your current view.",
    "Describe the objects around you.",
    "Is there anything notable in your vision?",
    "What's in the vicinity?",
    "Can you provide visual details?",
    "Tell me about your visual experience.",
    "Are you seeing any distinct objects?",
    "What's within your line of vision?",
    "Describe your visual perspective.",
    "Is there anything visible to you?",
    "Share your observations.",
    "Can you detect any specific items?",
    "Tell me about the things you can perceive visually.",
    "Describe what's happening in front of you.",
    "Are there any notable visuals?",
    "What's in your surroundings?",
    "Can you see any interesting objects?",
    "Tell me about the view in your vicinity.",
    "Describe your visual field.",
    "Is there anything eye-catching?",
    "Share your visual impressions with me.",
    "Can you make out any details?",
    "Tell me about the scene before you.",
    "Are there any items that stand out?",
    "What's in your direct line of sight?",
    "Describe what's in front of you right now.",
    "Are there any distinct visuals?",
    "Can you recognize any objects?",
    "Tell me about your visual perception.",
    "Describe what's within your gaze.",
    "Are you noticing any particular items?",
]
