# Greetings
greetings = [
    "How are you?",
    "Are you okay?",
    "Are you fine?",
    "How's your night?",
    "How's your day?",
    "How's everything?",
    "Is everything alright?",
    "How's your mood?",
    "How's your health?",
    "How's your week?",
    "How's your weekend?",
    "How's your appetite?",
    "How's the weather?",
    "How's your family?",
    "How's work?",
    "How's your commute?",
    "How's your evening?",
    "How's your lunch?",
    "How's your breakfast?",
    "How's your dinner?",
    "How's your mood today?",
    "How's your energy?",
    "How's your workday?",
    "How's your job?",
    "How's your day going?",
    "How's your night going?",
    "How's your day off?",
    "How's your lunchtime?",
    "How's your meal?",
    "How's your break?",
    "How's your work-life balance?",
    "How's your weekend going?",
    "How's your afternoon?",
    "How's your morning?",
    "How's your day shaping up?",
    "How's your day unfolding?",
    "How's your day at work?",
    "How's your hair today?",
    "How's your hair looking?",
    "How's your hair day?",
    "How's your hair holding up?",
    "How's your hair doing?",
    "How's your day off treating you?",
    "How's your evening looking?",
    "How's your evening so far?",
    "How's your day progressing?",
    "How's your workout today?",
    "How's your weekend treating you?",
    "How's your day off today?",
    "How's your night tonight?",
]

# Responses
responses = [
    "I'm good, thanks!",
    "Yes, I'm okay.",
    "Yes, I'm fine.",
    "My night was good.",
    "My day is going well.",
    "Everything's good.",
    "Yes, everything's fine.",
    "I'm in a good mood.",
    "I'm feeling healthy.",
    "My week is great so far.",
    "My weekend is going well.",
    "I have a good appetite.",
    "The weather is nice.",
    "My family is well, thanks.",
    "Work is fine.",
    "The commute was smooth.",
    "My evening is pleasant.",
    "Lunch was delicious.",
    "Breakfast was good.",
    "Dinner was great.",
    "I'm in a good mood today.",
    "My energy is high.",
    "Workday is going well.",
    "Job is fine, thanks.",
    "My day is going smoothly.",
    "Night is relaxing.",
    "Day off is enjoyable.",
    "Lunchtime is good.",
    "The meal was tasty.",
    "The break is refreshing.",
    "Balancing work and life.",
    "Weekend is fantastic.",
    "Afternoon is fine.",
    "Morning is good.",
    "Day is shaping up nicely.",
    "Day is unfolding well.",
    "Day at work is productive.",
    "Hair is looking great.",
    "Hair is doing fine.",
    "It's a good hair day.",
    "Hair is holding up well.",
    "Hair is looking good.",
    "Day off is treating me well.",
    "Evening looks promising.",
    "Evening is enjoyable.",
    "Day is progressing well.",
    "Workout was good.",
    "Weekend is treating me well.",
    "Day off is relaxing.",
    "Night is pleasant.",
]
